### ISSUE TITLE
[Bug] : [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by DenisDolgov** [cssnano/cssnano#1103]
When building the project, I get the error "[object Object] is not a PostCSS plugin". When using version 4 of cssnano everything is OK.

Here are my dependencies:

```
"devDependencies": {
    "clean-webpack-plugin": "^4.0.0-alpha.0",
    "copy-webpack-plugin": "^8.1.1",
    "cross-env": "^7.0.3",
    "css-loader": "^5.2.4",
    "css-minimizer-webpack-plugin": "^3.0.0",
    "cssnano": "^5.0.2",
    "expose-loader": "^2.0.0",
    "glob": "^7.1.7",
    "html-webpack-plugin": "^5.3.1",
    "imagemin-webpack-plugin": "^2.4.2",
    "imports-loader": "^2.0.0",
    "mini-css-extract-plugin": "^1.6.0",
    "node-sass": "^6.0.0",
    "nunjucks": "^3.2.3",
    "postcss-loader": "^5.3.0",
    "postcss-preset-env": "^6.7.0",
    "postcss-responsive-type": "^1.0.0",
    "sass-loader": "^11.1.1",
    "simple-nunjucks-loader": "^3.1.0",
    "style-loader": "^2.0.0",
    "svg-sprite-loader": "^6.0.6",
    "webpack": "^5.37.0",
    "webpack-cli": "^4.7.0",
    "webpack-merge": "^5.7.3"
  }
```

Here is my postcss config:

```
const postcssPresetEnv = require('postcss-preset-env');

module.exports = {
    plugins: [
        postcssPresetEnv({
            stage: 4
        }),
        require('cssnano')({
            preset: 'default'
        })
    ]
}
```

Here is the full text of the error:

ERROR in ./src/css/app.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!./src/css/app.scss)
  Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
  Error: [object Object] is not a PostCSS plugin
      at Processor.normalize (C:\projects\gala-webpack5\node_modules\postcss\lib\processor.js:145:15)
      at new Processor (C:\projects\gala-webpack5\node_modules\postcss\lib\processor.js:51:25)
      at postcss (C:\projects\gala-webpack5\node_modules\postcss\lib\postcss.js:73:10)
      at cssnanoPlugin (C:\projects\gala-webpack5\node_modules\cssnano\dist\index.js:137:31)
      at Object.<anonymous> (C:\projects\gala-webpack5\config\postcss.config.js:9:27)
      at Module._compile (C:\projects\gala-webpack5\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
      at Module.require (internal/modules/cjs/loader.js:952:19)
      at module.exports (C:\projects\gala-webpack5\node_modules\import-fresh\index.js:32:59)
      at loadJs (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\loaders.js:16:18)
      at Explorer.loadFileContent (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\Explorer.js:84:32)
      at Explorer.createCosmiconfigResult (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\Explorer.js:89:36)
      at runLoad (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\Explorer.js:103:33)
      at async cacheWrapper (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)

  Child mini-css-extract-plugin C:\projects\gala-webpack5\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[7].use[1]!C:\projects\gala-webpack5\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[7].use[2]!C:\projects\gala-webpack5\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[7].use[3]!C:\projects\gala-webpack5\src\css\app.scss compiled with 1 error

ERROR in ./src/css/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (C:\projects\gala-webpack5\node_modules\postcss\lib\processor.js:145:15)
    at new Processor (C:\projects\gala-webpack5\node_modules\postcss\lib\processor.js:51:25)
    at postcss (C:\projects\gala-webpack5\node_modules\postcss\lib\postcss.js:73:10)
    at cssnanoPlugin (C:\projects\gala-webpack5\node_modules\cssnano\dist\index.js:137:31)
    at Object.<anonymous> (C:\projects\gala-webpack5\config\postcss.config.js:9:27)
    at Module._compile (C:\projects\gala-webpack5\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at module.exports (C:\projects\gala-webpack5\node_modules\import-fresh\index.js:32:59)
    at loadJs (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\loaders.js:16:18)
    at Explorer.loadFileContent (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\Explorer.js:89:36)
    at runLoad (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\Explorer.js:103:33)
    at async cacheWrapper (C:\projects\gala-webpack5\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at processResult (C:\projects\gala-webpack5\node_modules\webpack\lib\NormalModule.js:690:19)
    at C:\projects\gala-webpack5\node_modules\webpack\lib\NormalModule.js:792:5
    at C:\projects\gala-webpack5\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\projects\gala-webpack5\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\projects\gala-webpack5\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\projects\gala-webpack5\node_modules\postcss-loader\dist\index.js:48:7)

**Comment by ludofischer** [comment]
Are you using PostCSS 7 or 8? cssnano 5 only works with PostCSS 8. I don't remember how postcss-loader works, but according to the [readme](https://github.com/webpack-contrib/postcss-loader) you should install postcss along postcss-loader, but there is no postcss in your `devDependencies`.

**Comment by alexander-akait** [comment]
Please add `postcss` to your package.json, run `npm install -D postcss`, postcss-loader requests `postcss` as peer dep, also please always read warnings/errors from your package manager, thanks
