### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gheydon** [cssnano/cssnano#1182]
### Describe the bug

Using tailwindcss with the border-styles plugin cssnano is crashing in certain situations.

### Expected behaviour

The expectation is that it will not crash.

### Steps to reproduce

I created a basic setup postcss setup with tailwindcss (not required as I have provided the output css.) 

```
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind screens;

.main {
  @apply border-opacity-20 border border-t-solid border-white border-l-none border-r-none border-b-none
}
```

This will produce the following code

```
.main {
  border-width: 1px;
  --tw-border-opacity: 1;
  border-color: rgba(255, 255, 255, var(--tw-border-opacity));
  --tw-border-opacity: 0.2;
  border-top-style: solid;
  border-right-style: none;
  border-bottom-style: none;
  border-left-style: none
}
```

I will then get the following error from cssnano

```
TypeError: Cannot read property '0' of undefined
    at /Users/gordon/Source/cssnano/issue-1/styles.css:6:1
    at /Users/gordon/Source/cssnano/issue-1/styles.css:3:1
    at _default (/Users/gordon/Source/cssnano/issue-1/node_modules/postcss-merge-longhand/dist/lib/parseTrbl.js:12:12)
    at mergeRedundant (/Users/gordon/Source/cssnano/issue-1/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:123:38)
    at /Users/gordon/Source/cssnano/issue-1/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:542:12
    at /usr/local/lib/node_modules/postcss/lib/container.js:85:16
    at /usr/local/lib/node_modules/postcss/lib/container.js:55:18
    at Rule.each (/usr/local/lib/node_modules/postcss/lib/container.js:41:16)
    at Rule.walk (/usr/local/lib/node_modules/postcss/lib/container.js:52:17)
    at Rule.walkDecls (/usr/local/lib/node_modules/postcss/lib/container.js:83:17)
    at Object.merge (/Users/gordon/Source/cssnano/issue-1/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:515:8)
    at /Users/gordon/Source/cssnano/issue-1/node_modules/postcss-merge-longhand/dist/index.js:20:13 {
  postcssNode: Rule {
    raws: { before: '', between: '', semicolon: false, after: '' },
    type: 'rule',
    nodes: [ [Declaration], [Declaration], [Declaration], [Declaration] ],
    parent: Root {
      raws: [Object],
      type: 'root',
      nodes: [Array],
      source: [Object],
      lastEach: 70,
      indexes: [Object],
      rawCache: [Object],
      _autoprefixerDisabled: false,
      _autoprefixerPrefix: false,
      _autoprefixerGridStatus: false,
      [Symbol(isClean)]: false,
      [Symbol(my)]: true,
      [Symbol(isClean)]: false
    },
    source: { start: [Object], input: [Input], end: [Object] },
    selector: '.main',
    lastEach: 60,
    indexes: { '60': 2 },
    _autoprefixerDisabled: false,
    _autoprefixerGridStatus: false,
    [Symbol(isClean)]: false,
    [Symbol(my)]: true,
    [Symbol(isClean)]: false
  }
}
```

### Version

5.0.7

### Preset

default

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 156.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Package details

```shell
├─┬ autoprefixer@10.3.1
│ └── postcss@8.3.6 deduped
├─┬ cssnano@5.0.7
│ ├─┬ cssnano-preset-default@5.1.3
│ │ ├─┬ css-declaration-sorter@6.1.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ cssnano-utils@2.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-calc@8.0.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-colormin@5.2.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-convert-values@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-discard-comments@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-discard-duplicates@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-discard-empty@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-discard-overridden@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-merge-longhand@5.0.2
│ │ │ ├── postcss@8.3.6 deduped
│ │ │ └─┬ stylehacks@5.0.1
│ │ │   └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-merge-rules@5.0.2
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-minify-font-values@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-minify-gradients@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-minify-params@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-minify-selectors@5.1.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-charset@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-display-values@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-positions@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-repeat-style@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-string@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-timing-functions@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-unicode@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-url@5.0.2
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-normalize-whitespace@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-ordered-values@5.0.2
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-reduce-initial@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-reduce-transforms@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-svgo@5.0.2
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-unique-selectors@5.0.1
│ │ │ └── postcss@8.3.6 deduped
│ │ └── postcss@8.3.6 deduped
│ └── postcss@8.3.6 deduped
├─┬ postcss-cli@8.3.1
│ ├─┬ postcss-reporter@7.0.2
│ │ └── postcss@8.3.6 deduped
│ └── postcss@8.3.6 deduped
├── postcss@8.3.6
└─┬ tailwindcss@2.2.7
  ├─┬ postcss-js@3.0.3
  │ └── postcss@8.3.6 deduped
  ├─┬ postcss-nested@5.0.5
  │ └── postcss@8.3.6 deduped
  ├── postcss@8.3.6 deduped
  └─┬ purgecss@4.0.3
    └── postcss@8.3.6 deduped
```

**Comment by sigveio** [comment]
Hey @gheydon! Thanks for your report. 

I can confirm that this appear to be a bug - it's tripping up on the `var()` inside a `rgba()` by the looks of it.

We are working on improving this plugin, so I will add this to the list.

**Comment by gheydon** [comment]
I just checked and tailwindcss uses this a lot, Here is an example the border-white utility class which uses this paradym.

```
.border-white{
  --tw-border-opacity: 1;
  border-color: rgba(255, 255, 255, var(--tw-border-opacity));
}
```

**Comment by ludofischer** [comment]
Maybe it is a more complex edge case, since at some point Tailwind was using cssnano by default, so if it always failed to minify we would have had more reports about it.

**Comment by sigveio** [comment]
> I just checked and tailwindcss uses this a lot, Here is an example the border-white utility class which uses this paradym.
> 
> ```
> .border-white{
>   --tw-border-opacity: 1;
>   border-color: rgba(255, 255, 255, var(--tw-border-opacity));
> }
> ```

I don't think it would actually error on this one by itself. It should only happen if the conditions for attempting to merge into a shorthand are met. Meaning there would have to be multiple border properties inside that rule for it to hit the problematic code. Which probably does not happen with the Tailwind's most common usage, applying utility classes directly to elements.

**Comment by ludofischer** [comment]
The input in this issue does not produce errors as of cssnano 8.0.5.
