### ISSUE TITLE
[Bug]: TypeError: plugin is not a function with Webpack 5.75.0 and postcss 8.4.20

### ISSUE THREAD

**Issue by turboMaCk** [cssnano/cssnano#1459]
### Describe the bug

webpack build using postcss fails with:

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: plugin is not a function
    at LazyResult.run (project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:212:26)
    at project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:131:17)
    at project/node_modules/postcss-loader/src/index.js:142:8
 @ ./web-components/code-editor.scss
```

### Expected behaviour

compilation with postcss config (taken from examples):

```
module.exports = {
    plugins: [
        require('cssnano')({
            preset: 'default',
        }),
    ],
};
```

should work

### Steps to reproduce

1. using webpack 5.75.0
2. using postcss 8.4.20
3. using cssnano 5.1.14
4. using example configuration:

```
module.exports = {
  plugins: [
    require('cssnano')({
      preset: 'default',
    }),
    // require("autoprefixer"),
  ]
};
```

should work. Instead build fails with exception in postcss-loader.

Example configuration is taken from https://cssnano.co/docs/getting-started/

### Version

5.1.14

### Preset

(no preset)

### Environment

```shell
System:
    OS: Linux 5.15 NixOS 23.05 (Stoat) 23.05 (Stoat)
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 21.18 GB / 31.27 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
```

### Package details

```shell
project@1.0.0 project
├─┬ autoprefixer@9.8.8
│ └── postcss@7.0.39
├─┬ css-loader@3.6.0
│ ├─┬ icss-utils@4.1.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-extract-imports@2.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-local-by-default@3.0.3
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-scope@2.2.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-values@3.0.0
│ │ └── postcss@7.0.39
│ └── postcss@7.0.39
├─┬ cssnano@5.1.14
│ ├─┬ cssnano-preset-default@5.2.13
│ │ ├─┬ css-declaration-sorter@6.3.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ cssnano-utils@3.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-calc@8.2.4
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-colormin@5.3.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-convert-values@5.1.3
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-comments@5.1.2
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-duplicates@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-empty@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-overridden@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-merge-longhand@5.1.7
│ │ │ ├── postcss@8.4.20 deduped
│ │ │ └─┬ stylehacks@5.1.1
│ │ │   └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-merge-rules@5.1.3
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-font-values@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-gradients@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-params@5.1.4
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-selectors@5.2.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-charset@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-display-values@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-positions@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-repeat-style@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-string@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-timing-functions@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-unicode@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-url@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-whitespace@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-ordered-values@5.1.3
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-reduce-initial@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-reduce-transforms@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-svgo@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-unique-selectors@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ └── postcss@8.4.20 deduped
│ └── postcss@8.4.20 deduped
├─┬ postcss-loader@3.0.0
│ └── postcss@7.0.39
└── postcss@8.4.20
```

### Additional context

Similar configuration was working as expected with webpack 4 and older versions of dependecies. Removing cssnano from postcss configuration fixes the build issue.

**Comment by alexander-akait** [comment]
```
├─┬ postcss-loader@3.0.0
│ └── postcss@7.0.39
```

You have multiple version of postcss and seems like try to run plugin on the old version of `postcss-loader`, please update `postcss-loader` to the latest version and check `postcss` version in your `package.json`

**Comment by turboMaCk** [comment]
I'm unable to make sure I get just one version of postcss because of all the peer dependecies madness involved. However I was able to somehow get to the point where I at least get this set of versions:

```
pi-frontend@1.0.0 /home/marek/Projects/holmusk/PI/frontend
├─┬ autoprefixer@9.8.8
│ └── postcss@7.0.39
├─┬ css-loader@3.6.0
│ ├─┬ icss-utils@4.1.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-extract-imports@2.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-local-by-default@3.0.3
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-scope@2.2.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-values@3.0.0
│ │ └── postcss@7.0.39
│ └── postcss@7.0.39
├─┬ cssnano@5.1.14
│ ├─┬ cssnano-preset-default@5.2.13
│ │ ├─┬ css-declaration-sorter@6.3.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ cssnano-utils@3.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-calc@8.2.4
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-colormin@5.3.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-convert-values@5.1.3
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-comments@5.1.2
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-duplicates@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-empty@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-discard-overridden@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-merge-longhand@5.1.7
│ │ │ ├── postcss@8.4.20 deduped
│ │ │ └─┬ stylehacks@5.1.1
│ │ │   └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-merge-rules@5.1.3
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-font-values@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-gradients@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-params@5.1.4
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-minify-selectors@5.2.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-charset@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-display-values@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-positions@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-repeat-style@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-string@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-timing-functions@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-unicode@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-url@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-normalize-whitespace@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-ordered-values@5.1.3
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-reduce-initial@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-reduce-transforms@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-svgo@5.1.0
│ │ │ └── postcss@8.4.20 deduped
│ │ ├─┬ postcss-unique-selectors@5.1.1
│ │ │ └── postcss@8.4.20 deduped
│ │ └── postcss@8.4.20 deduped
│ └── postcss@8.4.20
└─┬ postcss-loader@7.0.2
  └── postcss@8.4.20 deduped
```

which seems to fix the issue. I believe the `postcss-loader@7.0.2` is the important part.

Thanks
