### ISSUE TITLE
postcss-svgo@4.0.0 is incompatible with svgo@1.1.0

### ISSUE THREAD

**Issue by ladjzero** [cssnano/cssnano#603]
Cloned from https://github.com/ben-eb/postcss-svgo/issues/61 because the repo postcss-svgo was migrated to here.

```
TypeError: Cannot read property 'path' of undefined
    at optimizeOnceCallback (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:48:29)
    at /home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:70:9
    at SAXParser.sax.onend (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo/svg2js.js:169:13)
    at emit (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:624:35)
    at end (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.write (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:975:14)
    at SAXParser.close (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo/svg2js.js:182:28)
    at SVGO._optimizeOnce (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:62:5)
    at Promise (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:55:14)
    at new Promise (<anonymous>)
    at SVGO.optimize (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:25:12)
    at decl.value.walk.node (/home/chenzhuo/repos/activityengine/node_modules/postcss-svgo/dist/index.js:69:28)
```

Relates to svg/svgo#1030

**Comment by yqz0203** [comment]
I fixed it by install svgo@1.0.0 manually.☹️☹️

**Comment by andyjansson** [comment]
Thanks for the report. Looks like svgo released a new version 15 hours ago. The fix will likely be applied upstream, but I'll monitor the thread just in case.

**Comment by evilebottnawi** [comment]
https://github.com/svg/svgo/issues/1030#issuecomment-421931404 some body can reproduce bug now?
