### ISSUE TITLE
Merge-rules conflicts with autoprefixer grid option

### ISSUE THREAD

**Issue by FreekVR** [cssnano/cssnano#638]
I'm running a postcss stack with both autoprefixer with 'grid: true' on, and running cssnano with the 'default' preset. It appears the  "mergeRules" option isn't working correctly with the autoprefixer grid options (I get this error, unless I disable either the mergeRules or the grid option of autoprefixer)

```
TypeError in plugin "gulp-postcss"
Message:
    Cannot destructure property `name` of 'undefined' or 'null'.
Details:
    postcssNode: .layout__header{
    -ms-grid-row:1;
    -ms-grid-column:1}
    fileName: frontend/src/assets/styles/app.css

Stack:
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at frontend/src/assets/styles/app.css:1515:1
    at canMerge (frontend/node_modules/postcss-merge-rules/dist/index.js:63:28)
    at frontend/node_modules/postcss-merge-rules/dist/index.js:192:24
    at frontend/node_modules/postcss/lib/container.js:239:18
    at frontend/node_modules/postcss/lib/container.js:135:18
    at AtRule.each (frontend/node_modules/postcss/lib/container.js:101:16)
    at AtRule.walk (frontend/node_modules/postcss/lib/container.js:131:17)
    at frontend/node_modules/postcss/lib/container.js:148:24
    at Root.each (frontend/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (frontend/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (frontend/node_modules/postcss/lib/container.js:237:19)
```

Here's my unprefixed source file:

```
.layout {
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: @navigation-height-mobile auto auto;
    grid-template-areas: 'layout-header' 'layout-main';
    grid-gap: @grid-gap;

    @media @q-lg-min {
        /** Redeclare entire grid for IE11 autoprefix compatbility **/
        grid-gap: @grid-gap-lg;
        grid-template-columns: 1fr;
        grid-template-areas: 'layout-header' 'layout-main';
        grid-template-rows: @navigation-height-desktop auto auto;
    }
}

.layout__header {
    grid-area: layout-header;
}

.layout__main {
    grid-area: layout-main;
}

.layout__aside {
    grid-area: layout-aside;
}

.layout__footer {
    grid-area: layout-footer;
    align-self: end;
}
```

Here's my config (using gulp)
```
const processors = [
        autoprefixer({
            cascade: false,
            grid: true
        }),
        cssnano({preset: ['default', {
            zindex: false,
            //mergeRules: true
        }]})
    ];

(...)
.pipe(postcss(processors)) 
(...)
```

**Comment by andyjansson** [comment]
Can you provide the compiled CSS for this, too? Looks like you're using Less.

**Comment by FreekVR** [comment]
Sure thing! Here's what that compiles to with autoprefixer

```.layout {
  max-width: 1400px;
  padding-left: 1rem;
  padding-right: 1rem;
  margin: 0 auto;
  display: -ms-grid;
  display: grid;
  -ms-grid-columns: 1fr;
  grid-template-columns: 1fr;
  -ms-grid-rows: 3rem 1rem auto 1rem auto;
  grid-template-rows: 3rem auto auto;
  grid-template-areas: 'layout-header' 'layout-main';
  grid-gap: 1rem;
}
@media screen and (min-width: 769px ) {
  .layout {
    padding-left: 2rem;
    padding-right: 2rem;
  }
}
@media screen and (min-width: 769px ) {
  .layout {
    /** Redeclare entire grid for IE11 autoprefix compatbility **/
    grid-gap: 1.5rem;
    -ms-grid-columns: 1fr;
    grid-template-columns: 1fr;
    grid-template-areas: 'layout-header' 'layout-main';
    -ms-grid-rows: 3rem 1.5rem auto 1.5rem auto;
    grid-template-rows: 3rem auto auto;
  }
}
.layout__header {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
  grid-area: layout-header;
}
.layout--sidebar > .layout__header {
  -ms-grid-row: 1;
  -ms-grid-column: 1;
}
.layout__main {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: layout-main;
}
.layout--sidebar > .layout__main {
  -ms-grid-row: 5;
  -ms-grid-column: 1;
}
.layout__aside {
  -ms-grid-row: 3;
  -ms-grid-column: 1;
  grid-area: layout-aside;
}
.layout__footer {
  -ms-grid-row: 7;
  -ms-grid-column: 1;
  grid-area: layout-footer;
  -ms-flex-item-align: end;
  -ms-grid-row-align: end;
  align-self: end;
}
@media screen and (min-width: 769px ){
  .layout__header {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
  }
  .layout__main {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
}
.layout--sidebar {
  -ms-grid-columns: 1fr;
  grid-template-columns: 1fr;
  -ms-grid-rows: 3rem 1rem auto 1rem auto 1rem auto;
  grid-template-rows: 3rem auto auto auto;
  grid-template-areas: 'layout-header' 'layout-aside' 'layout-main' 'layout-footer';
  grid-gap: 1rem;
}
@media screen and (min-width: 769px ) {
  .layout--sidebar {
    /** Redeclare entire grid for IE11 autoprefix compatbility **/
    -ms-grid-columns: 35% 1.5rem auto;
    grid-template-columns: 35% auto;
    -ms-grid-rows: 3rem 1.5rem auto 1.5rem auto;
    grid-template-rows: 3rem auto auto;
    grid-template-areas: 'layout-header layout-header' 'layout-aside layout-main' 'layout-footer layout-footer';
    grid-gap: 1.5rem;
  }
  .layout--sidebar > .layout__header {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
    -ms-grid-column-span: 3;
  }
  .layout--sidebar > .layout__main {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
  .layout__aside {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .layout__footer {
    -ms-grid-row: 5;
    -ms-grid-column: 1;
    -ms-grid-column-span: 3;
  }
}
@media screen and (min-width: 1201px ) {
  .layout--sidebar {
    /** Redeclare entire grid for IE11 autoprefix compatbility **/
    -ms-grid-columns: 25rem 1.5rem auto;
    grid-template-columns: 25rem auto;
    -ms-grid-rows: 3rem 1.5rem auto 1.5rem auto;
    grid-template-rows: 3rem auto auto;
    grid-template-areas: 'layout-header layout-header' 'layout-aside layout-main' 'layout-footer layout-footer';
    grid-gap: 1.5rem;
  }
  .layout--sidebar > .layout__header {
    -ms-grid-row: 1;
    -ms-grid-column: 1;
    -ms-grid-column-span: 3;
  }
  .layout--sidebar > .layout__main {
    -ms-grid-row: 3;
    -ms-grid-column: 3;
  }
  .layout__aside {
    -ms-grid-row: 3;
    -ms-grid-column: 1;
  }
  .layout__footer {
    -ms-grid-row: 5;
    -ms-grid-column: 1;
    -ms-grid-column-span: 3;
  }
}```

**Comment by andyjansson** [comment]
I can't seem to reproduce.

**Comment by FreekVR** [comment]
Okay, there's some weird stuff going on here.

Running postcss with autoprefixer, then feeding that prefixed css (as in my previous comment) to cssnano, works fine.

However, running an _unprefixed_ css file through postcss with BOTH the autoprefixer and cssnano plugins on, returns the error.

(running the most recent autoprefixer, postcss, cssnano versions)
Here's the css in that scenario
```
.layout {
    max-width: 1400px;
    padding-left: 1rem;
    padding-right: 1rem;
    margin: 0 auto;
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: 3rem auto auto;
    grid-template-areas: 'layout-header' 'layout-main';
    grid-gap: 1rem;
}
@media screen and (min-width: 769px ) {
    .layout {
        /** Redeclare entire grid for IE11 autoprefix compatbility **/
        grid-gap: 1.5rem;
        grid-template-columns: 1fr;
        grid-template-areas: 'layout-header' 'layout-main';
        grid-template-rows: 3rem auto auto;
    }
}
.layout__header {
    grid-area: layout-header;
}
.layout__main {
    grid-area: layout-main;
}
.layout__aside {
    grid-area: layout-aside;
}
.layout__footer {
    grid-area: layout-footer;
    align-self: end;
}
```
And here's my postcss config file
```
module.exports = {
    plugins: [
        require('autoprefixer')({
            //cascade: false,
            grid: true
        }),
        require('cssnano')({preset: ['default', {
                //mergeRules: false // Disabling mergerules fixes errors
        }]})
    ]
};
```
Running `postcss input.css > output.css` on this will result in the error as in the first post, little more debug info from the CLI that may be relevant though:

```
{ TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at phpstormprojects/fwf-member-portal/frontend/input.css:21:1
    at canMerge postcss-merge-rules/dist/index.js:63:28)
    at phpstormprojects/fwf-member-portal/frontend/node_modules/postcss-merge-rules/dist/index.js:192:24
    at .config/yarn/global/node_modules/postcss/lib/container.js:239:18
    at .config/yarn/global/node_modules/postcss/lib/container.js:135:18
    at AtRule.each /.config/yarn/global/node_modules/postcss/lib/container.js:101:16)
    at AtRule.walk /.config/yarn/global/node_modules/postcss/lib/container.js:131:17)
    at .config/yarn/global/node_modules/postcss/lib/container.js:148:24
    at Root.each /.config/yarn/global/node_modules/postcss/lib/container.js:101:16)
    at Root.walk /.config/yarn/global/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules /.config/yarn/global/node_modules/postcss/lib/container.js:237:19)
  postcssNode:
   Rule {
     raws: { before: '', between: '', semicolon: false, after: '' },
     type: 'rule',
     nodes: [ [Object], [Object] ],
     source: { start: [Object], input: [Object], end: [Object] },
     selector: '.layout__header',
     lastEach: 49,
     indexes: { '14': 4 },
     _autoprefixerDisabled: false,
     _autoprefixerGridStatus: true,
     _autoprefixerPrefix: false,
     rawCache: { beforeRule: '\n', beforeDecl: '\n', indent: '    ' } } }
```

**Comment by andyjansson** [comment]
>it must be something autoprefixer is doing to the AST perhaps?

Yes, I'd wager this is the case. I managed to reproduce the issue now, and it looks like the `.layout__header` rule is missing its parent.

**Comment by andyjansson** [comment]
\cc @ai

**Comment by ai** [comment]
@bogdan0083 do we insert rules in a tricky way so they can lose `rule.parent` in new Autoprefixer?

**Comment by ai** [comment]
I found mistake

**Comment by ai** [comment]
Fixed

**Comment by andyjansson** [comment]
Great!

**Comment by ai** [comment]
Released in 9.2.1

**Comment by bogdan0083** [comment]
@ai Wow. Can you please tell me what I did wrong and why the parent went missing? 😄

How does this breaks the parent:
```js
lastRule.after({ name: 'media', nodes: data[params], params })

```

and this does not:

```js
lastRule.after({ name: 'media', params })
lastRule.next().append(data[params])
```

**Comment by FreekVR** [comment]
Wow, thanks for getting op top of this so quickly and fixing this guys! <3
