### ISSUE TITLE
error in postcss-merge-longhand

### ISSUE THREAD

**Issue by aldarund** [cssnano/cssnano#644]
this code
```.el-step__icon.is-text{border-radius:50%;border:2px solid;border-color:inherit}```

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'search' of undefined
    at d:\bb\аа\node_modules\element-ui\lib\theme-chalk\index.css:1:1
    at isValueCustomProp (d:\bb\аа\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:106:45)
    at d:\bb\аа\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:449:18
    at mergeRules (d:\bb\аа\node_modules\postcss-merge-longhand\dist\lib\mergeRules.js:46:17)
    at wsc.forEach (d:\bb\аа\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (d:\bb\аа\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:436:9)
    at _decl2.default.forEach.p (d:\bb\аа\node_modules\postcss-merge-longhand\dist\index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (d:\bb\аа\node_modules\postcss-merge-longhand\dist\index.js:20:28)
    at d:\bb\аа\node_modules\postcss\lib\container.js:239:18
    at d:\bb\аа\node_modules\postcss\lib\container.js:135:18
    at Root.each (d:\bb\аа\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (d:\bb\аа\node_modules\postcss\lib\container.js:131:17)
    at Root.walkRules (d:\bb\аа\node_modules\postcss\lib\container.js:237:19)
    at css (d:\bb\аа\node_modules\postcss-merge-longhand\dist\index.js:19:13)
    at initializePlugin (d:\bb\аа\node_modules\cssnano\dist\index.js:35:51)
 @ ./node_modules/element-ui/lib/theme-chalk/index.css 4:14-140
```
It break element-ui framework

**Comment by evilebottnawi** [comment]
Already fixed in master
