### ISSUE TITLE
cssnano depends on deprecated/old version of postcss-discard-comments which causes bug

### ISSUE THREAD

**Issue by foresightyj** [cssnano/cssnano#728]
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.14, but postcss-discard-comments uses 4.1.16. Perhaps this is the source of the error below.

events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: css.eachInside is not a function
    at D:\Working\FHT.Web\node_modules\_postcss-discard-comments@1.2.1@postcss-discard-comments\index.js:30:13
    at LazyResult.run (D:\Working\FHT.Web\node_modules\_postcss@7.0.14@postcss\lib\lazy-result.js:295:14)
    at LazyResult.asyncTick (D:\Working\FHT.Web\node_modules\_postcss@7.0.14@postcss\lib\lazy-result.js:208:26)
    at LazyResult.asyncTick (D:\Working\FHT.Web\node_modules\_postcss@7.0.14@postcss\lib\lazy-result.js:221:14)
    at D:\Working\FHT.Web\node_modules\_postcss@7.0.14@postcss\lib\lazy-result.js:213:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fht-web@1.0.0 scss: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fht-web@1.0.0 scss script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-04-09T01_59_00_374Z-debug.log

**Comment by foresightyj** [comment]
Sorry. I reinstalled cssnano and the problem is gone.
