### ISSUE TITLE
[Bug] : TypeError: (0 , _cosmiconfig.cosmiconfig) is not a function

### ISSUE THREAD

**Issue by RyanChristian4427** [cssnano/cssnano#948]
**Describe the bug**

I'm trying to use `cssnano@nightly` but I keep running up against the following:

```
TypeError: (0 , _cosmiconfig.cosmiconfig) is not a function

at resolveConfig (node_modules/cssnano/dist/index.js:104:26)
```

**To Reproduce**

Currently trying to update [`optimize-css-assets-webpack-plugin`](https://github.com/NMFR/optimize-css-assets-webpack-plugin). My fork that reproduces this bug can be found [here](https://github.com/RyanChristian4427/optimize-css-assets-webpack-plugin).

1. Install dependencies with `npm install`
2. Run the test suite with `npm test`

The error should be displayed.

**Expected behavior**

The test suite should complete, and theoretically do so without errors.

I mention below a work-around that gets the test suite to pass, and while I fixed a bug in the upgrade to `cssnano@nightly`, more might exist. It's entirely possible for the test suite to fail even after this is fixed, so it's a loose expectation for the test suite to pass.

**Screenshots**

N/A

**Desktop (please complete the following information):**

`npx envinfo`:

```
System:
    OS: Linux 5.7 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.32 GB / 11.67 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.npm-global/bin/npm
```

`npm ls cssnano`:

```
optimize-css-assets-webpack-plugin@5.0.4 /home/ryun/Projects/optimize-css-assets-webpack-plugin
└── cssnano@4.0.0-nightly.2020.9.1 
```

**Additional context**

While I know very little in this area, I noticed in an older version there was the following code:

```
var _cosmiconfig = require("cosmiconfig");

var _cosmiconfig2 = _interopRequireDefault(_cosmiconfig);

...

const configExplorer = (0, _cosmiconfig2.default)(cssnano);
```

Nightly looks like the following:

```
var _cosmiconfig = require("cosmiconfig");

...

const configExplorer = (0, _cosmiconfig.cosmiconfig)(cssnano);
```

Going back to the old version seems to work just fine, the test suite will run without throwing this error. Though, again, have very little understanding in this area, it's likely going back to whatever generated this built output is not a valid fix.

**Comment by evilebottnawi** [comment]
Why you transpile `node_modules`? Anyway `optimize-css-assets-webpack-plugin` is bad solution with many bugs, also no caches and parallels, we have official plugin for wepback https://github.com/webpack-contrib/css-minimizer-webpack-plugin

**Comment by RyanChristian4427** [comment]
Sorry, do you mean to ask why the plugin transpiles? I don't think I have, as for the plugin, no clue. I know next to nothing about what it does, just trying to fix an error.

Thanks for the information though. It's not that I use it, but that the [Preact CLI](https://github.com/preactjs/preact-cli) does. Trying to close an old 1% opacity bug, figured I'd help `optimize-css-assets-webpack-plugin`'s author use `cssnano@nightly` now that I see it's out.

**Comment by evilebottnawi** [comment]
I will look at issue in near future

**Comment by RyanChristian4427** [comment]
Cheers. I'll provide a link to this in the Preact CLI so that people much more informed than I can see your thoughts on the matter.

**Comment by anikethsaha** [comment]
I am not able to reproduce this issue. 

Can you send a repo without the plugin you mentioned? Just an independent repro using cssnano nightly. 
it would be great to have it as codesandbox as well.

**Comment by evilebottnawi** [comment]
Can't reproduce too

**Comment by RyanChristian4427** [comment]
Sorry, but the whole issue is that the forked plugin, when upgraded to use `cssnano@nightly`, fails its test suite. There is no other repo I can really give? The issue is entirely in that plugin's test suit. 

I'll try it again shortly to see if somehow the issue entirely went away.

**Comment by evilebottnawi** [comment]
@RyanChristian4427 maybe you have invalid environment for tests

**Comment by RyanChristian4427** [comment]
Don't know then. All I have is that repo and the tests are absolutely still failing due to `cssnano` for me. Not anything related to the actual plugin, just `cssnano`. 

```
TypeError: (0 , _cosmiconfig.cosmiconfig) is not a function

      72 |     return this.options
      73 |       .cssProcessor.process(css.source, processOptions, this.options.cssProcessorPluginOptions)
    > 74 |       .then(r => {
         |        ^
      75 |         if (processOptions.map && r.map && r.map.toString) {
      76 |           assets.setAsset(`${assetInfo.path}.map${assetInfo.query}`, r.map.toString());
      77 |         }

      at resolveConfig (node_modules/cssnano/dist/index.js:104:55)
      at plugin (node_modules/cssnano/dist/index.js:141:12)
```

**Comment by evilebottnawi** [comment]
Please open an issue in repo plugin, sorry I can't help you

**Comment by evilebottnawi** [comment]
Please migrate on https://github.com/webpack-contrib/css-minimizer-webpack-plugin, I will say again that the plugin is not designed correctly and does not support all webpack features

**Comment by RyanChristian4427** [comment]
For what it's worth, I was able to get a [codesandbox up here that reproduces](https://codesandbox.io/s/gallant-mountain-lzugk). Simply run `yarn test` in the terminal.

I find codesandbox to be incredibly uncomfortable to work with, and as such had to idea how to get es6 imports working, so the code is a bit different from the actual plugin. Still though, the error pops up. I hope that's good enough.

As for swapping it out entirely, I get your point but I'm don't I'm the one to do it. Like I mentioned, just came across this while helping with Preact's CLI. I'll mention it though.

**Comment by anikethsaha** [comment]
Thanks for your time. I suppose it is an issue with the plugin's setup/environment. 
the nightly version is working fine when used independently and with postcss config.

**Comment by RyanChristian4427** [comment]
Alright, well figure I may as well close this. If it's just an issue with how another library uses this one, then there's nothing for you to fix, and an alternative has been presented. Thank you two for your help.

**Comment by evilebottnawi** [comment]
@RyanChristian4427 Still in my TODO, let's keep open, I will give you advises why it is broken

**Comment by evilebottnawi** [comment]
@RyanChristian4427 Very strange, in our source code we have
```js
const configExplorer = (0, _cosmiconfig.default)(cssnano);
```

But in `cssnano@4.0.0-nightly.2020.9.1` we have:
```js
 const configExplorer = (0, _cosmiconfig.cosmiconfig)(cssnano);
```

@anikethsaha Looks we have bugs, do you run something (maybe babel) on `cssnano-nightly`?

**Comment by evilebottnawi** [comment]
hm, after run `yarn` in `cssnano` repo I got same problem, very weird :confused:

**Comment by anikethsaha** [comment]
We didn't have any changes related to cosmic afer 20 Jul 
https://github.com/cssnano/cssnano/pull/924

**Comment by anikethsaha** [comment]
> hm, after run `yarn` in `cssnano` repo I got the same problem, very weird 😕

This is really weird, I am not seeing this. 
I will try cleaning the node_modules and check

**Comment by evilebottnawi** [comment]
@anikethsaha hm, I think here other problem, give a sec

**Comment by evilebottnawi** [comment]
@anikethsaha 
```bash
yarn add cssnano@4.0.0-nightly.2020.9.3
// npm i cssnano@4.0.0-nightly.2020.9.3
```

Go to `node_modules/cssnano/package.json`

```json
{
  "dependencies": {
    "cosmiconfig": "^5.2.1",
    "cssnano-preset-default": "nightly",
    "is-resolvable": "^1.1.0",
    "opencollective-postinstall": "^2.0.2",
    "postcss": "^7.0.16"
  }
}
```

But in master we have https://github.com/cssnano/cssnano/blob/master/packages/cssnano/package.json#L28

**Comment by anikethsaha** [comment]
https://github.com/cssnano/cssnano-nightly/blob/master/dependenciesList.js#L5
We need to update this one

**Comment by evilebottnawi** [comment]
@anikethsaha we should not have hardcored deps, this array should be:
```
cssnano: {
    "cssnano-preset-default": version,
  },
```

so change only necessary deps and keep as it others

**Comment by anikethsaha** [comment]
We are using `edit-json-file` for changing the `package.json` and so I need to look whether we can do assign operation for the object instead of Overriding it. 
I will look into this as soon as possible.

**Comment by evilebottnawi** [comment]
@RyanChristian4427 https://github.com/cssnano/cssnano-nightly/pull/3/
