### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: css.walk is not a function

### ISSUE THREAD

**Issue by lu-yuan** [cssnano/cssnano#960]
E:\2020\front-end>yarn run build:css
yarn run v1.9.4
$ postcss css/tailwind.css -o src/theme/tailwind.css
(node:4452) UnhandledPromiseRejectionWarning: TypeError: css.walk is not a function
    at css (E:\2020\front-end\node_modules\postcss-discard-comments\dist\index.js:67:13)
    at initializePlugin (E:\2020\front-end\node_modules\cssnano\dist\index.js:31:51)
(node:4452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 4.37s.

====

const purgecss = require('@fullhuman/postcss-purgecss')
const cssnano = require('cssnano')

module.exports = {
  // 使用这个移除没有用到的CSS
  theme: {
    extend: {
    },
  },
  plugins: [
    cssnano({
      preset: 'default'
    })
  ]
};

**Comment by evilebottnawi** [comment]
Don't know, please use the issue template, hard to debug this

**Comment by lu-yuan** [comment]
Thank you.

**Comment by evilebottnawi** [comment]
What is `postcss` version?

**Comment by evilebottnawi** [comment]
Closing due to inactivity. We don't support PostCSS 8 right now

**Comment by Mistic92** [comment]
I have the same issue
```
    "mini-css-extract-plugin": "^1.6.2",
    "node-sass": "4.14.1",
    "postcss": "^7.0.36",
    "postcss-loader": "^4.3.0",
    "sass-loader": "8.0.2",
 ```

**Comment by ludofischer** [comment]
> I have the same issue

What cssnano version are you using? With postcss 7 you need cssnano 4. If you use postcss 8 you need cssnano 5.

**Comment by Mistic92** [comment]
```    "cssnano": "^4.1.11",```

**Comment by ludofischer** [comment]
> ` "cssnano": "^4.1.11",`

So the cssnano and postcss versions seem  to match. From the dependencies you've listed it looks like you're using webpack, it's going to be difficult to find out what's happening without a complete repository. On top of that we don't really maintain cssnano 4 and postcss 7 is also not actively maintained.

**Comment by NatumanyaGuy** [comment]
I got the same issue, turned out elements with classes; group and group-hover:[class] were NOT **parent** and **child** respectively. Did you use group class in your project, if yes review!

**Comment by christian-valadez** [comment]
> I got the same issue, turned out elements with classes; "group" and "group-[action - e.g. _hover_]:[class]" were NOT **parent** and **child** respectively. Did you use group class in your project? If yes review!

Thank you! I was stuck on this for weeks and it turned out to be this for me as well.
