### ISSUE TITLE
[Bug] : Unknown error using cssnano with postcss

### ISSUE THREAD

**Issue by Shoplifter** [cssnano/cssnano#987]
when running following command (cli), `postcss web/src/*.css -u cssnano -d web/min --no-map `I get this errror:
````
Unknown error from PostCSS plugin. Your current PostCSS version is 8.2.4, but cssnano uses 7.0.35. Perhaps this is the source of the error below.
Error [BrowserslistError]: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (C:\Users\XY\AppData\Roaming\npm\node_modules\cssnano\node_modules\browserslist\index.js:285:10)
    at C:\Users\XY\AppData\Roaming\npm\node_modules\cssnano\node_modules\browserslist\index.js:372:11
    at Array.reduce (<anonymous>)
    at resolve (C:\Users\XY\AppData\Roaming\npm\node_modules\cssnano\node_modules\browserslist\index.js:318:18)
    at browserslist (C:\Users\XY\AppData\Roaming\npm\node_modules\cssnano\node_modules\browserslist\index.js:444:21)
    at C:\Users\XY\AppData\Roaming\npm\node_modules\cssnano\node_modules\postcss-reduce-initial\dist\index.js:34:53
    at initializePlugin (C:\XY\baum\AppData\Roaming\npm\node_modules\cssnano\dist\index.js:31:51)
    at async LazyResult.runAsync (C:\Users\XY\AppData\Roaming\npm\node_modules\postcss\lib\lazy-result.js:358:11)
    at async Promise.all (index 2) {
  browserslist: true
}
````
I've been using this script for a long time, this happended only after the latest updates.

https://github.com/postcss/postcss/issues/1521

**Comment by alexander-akait** [comment]
There is not unknow errors, read the text, cssnano is not supported PostCSS v8 yet, but it is in master
